# Generated by Django 5.2.17 on 2026-09-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('setor', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('papel', models.CharField(choices=[('EXTERNO', 'Externo'), ('EP', 'Ep')], default='EXTERNO', max_length=100)),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
