# Generated by Django 5.2.17 on 2026-09-23 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('papel', models.CharField(choices=[('EXTERNO', 'Externo'), ('EP', 'Ep')], default='EXTERNO', max_length=100)),
                ('peso', models.IntegerField()),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Nome', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
