# Generated by Django 5.2.17 on 2026-09-23 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='mail',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Nome', to=settings.AUTH_USER_MODEL),
        ),
    ]
