# Generated by Django 5.2.17 on 2026-09-23 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='mail',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
