# Generated by Django 5.2.17 on 2026-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_usuarios_mail_alter_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
