# Generated by Django 5.2.17 on 2026-09-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_usuario_id_usuarios_usuario_usuarios_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
