# Generated by Django 5.2.17 on 2026-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usuarios_area_alter_usuarios_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='setor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
