# Generated by Django 5.2.17 on 2026-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_usuarios_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
